Cleanup
sangm/ember-scoped-query-cache pull request #5
Opened 2017-05-22 21:58 UTC by stefanpenner

- remove typeOf vs typeof ambiguity (opting for explicit)
- add `QueryCache.protototype.has` to avoid private usage

2017-05-22 23:10 UTC, scalvert requested changes

2017-05-22 23:10 UTC, scalvert commented on addon/utils/query-cache.js
> +  has(type, key) {
Should we call this `contains`? This seems to be fairly conventional for a cache API.

2017-05-22 23:21 UTC, stefanpenner commented on addon/utils/query-cache.js
> +  has(type, key) {
I was mimicing `Map.prototype.has` etc

2017-05-23 16:19 UTC, scalvert commented on addon/utils/query-cache.js
> +  has(type, key) {
¯\_(ツ)_/¯

2017-05-23 16:19 UTC, scalvert approved these changes

2017-05-23 16:20 UTC, merged

2017-05-23 16:22 UTC, stefanpenner commented on addon/utils/query-cache.js
> +  has(type, key) {
i can gladly swap, your call.